package com.github.karsaig.approvalcrest.matcher.overwrite;

import com.github.karsaig.approvalcrest.matcher.AbstractFileMatcherTest;
import com.github.karsaig.approvalcrest.matcher.JsonMatcher;
import com.github.karsaig.approvalcrest.testdata.BeanWithPrimitives;
import com.github.karsaig.approvalcrest.testdata.Person;
import com.github.karsaig.approvalcrest.util.PreBuilt;
import com.github.karsaig.approvalcrest.util.InMemoryFiles;
import com.github.karsaig.approvalcrest.util.InMemoryFsInfo;
import org.hamcrest.MatcherAssert;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;

import static java.util.Collections.singletonList;
import static org.junit.jupiter.api.Assertions.assertIterableEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * {@code fileMatcherSkipCustomMatchersOnUpdate} — letting a regeneration run get past a failing custom matcher.
 *
 * <p>A run with {@code -DfileMatcherUpdateInPlace=true} exists to rewrite approved files after an intentional
 * change. Custom matchers are evaluated before the comparison and stop the assertion on the first failure, so
 * such a run dies before most files are rewritten. The flag leaves them unevaluated, for that kind of run only.
 *
 * <p>Two things it deliberately does not do, both pinned below. It changes nothing unless an update is running,
 * and it suppresses only the assertion a registration carries — the field removal that {@code with} drives stays
 * on, because the file a regeneration writes has to be the one a verification run will compare against.
 */
public class JsonMatcherOverwriteSkipCustomMatchersTest extends AbstractFileMatcherTest {

    private static final String APPROVED_PATH = "4ac405/11b2ef-approved.json";
    private static final String HEADER = "/*dummyTestClassName.dummyTestMethodName*/\n";

    /** An approved file that has drifted from the actual bean, so a rewrite has something to do. */
    private static final String DRIFTED = HEADER +
            "{\n" +
            "  \"beanBoolean\": false,\n" +
            "  \"beanByte\": 99,\n" +
            "  \"beanChar\": \"z\",\n" +
            "  \"beanDouble\": 9.0,\n" +
            "  \"beanFloat\": 9.0,\n" +
            "  \"beanLong\": 99,\n" +
            "  \"beanShort\": 99\n" +
            "}";

    /** What the actual bean serialises to once a path registration has stripped {@code beanInteger}. */
    private static final String REGENERATED_WITHOUT_INTEGER = HEADER +
            "{\n" +
            "  \"beanBoolean\": true,\n" +
            "  \"beanByte\": 2,\n" +
            "  \"beanChar\": \"c\",\n" +
            "  \"beanDouble\": 5.0,\n" +
            "  \"beanFloat\": 3.0,\n" +
            "  \"beanLong\": 6,\n" +
            "  \"beanShort\": 1\n" +
            "}";

    /** The same bean with nothing stripped — what the additional mode leaves in the file. */
    private static final String REGENERATED_WITH_INTEGER = HEADER +
            "{\n" +
            "  \"beanBoolean\": true,\n" +
            "  \"beanByte\": 2,\n" +
            "  \"beanChar\": \"c\",\n" +
            "  \"beanDouble\": 5.0,\n" +
            "  \"beanFloat\": 3.0,\n" +
            "  \"beanInteger\": 4,\n" +
            "  \"beanLong\": 6,\n" +
            "  \"beanShort\": 1\n" +
            "}";

    private Path approvedFile(InMemoryFsInfo imfsi) {
        return imfsi.getTestPath().resolve("4ac405").resolve("11b2ef-approved.json");
    }

    private void assertApprovedFileIs(InMemoryFsInfo imfsi, String expectedContent) {
        assertIterableEquals(singletonList(new InMemoryFiles(APPROVED_PATH, expectedContent)), getFiles(imfsi));
    }

    // --- the flag does its job ---

    /**
     * The regenerated bytes have to be what a run whose matcher <em>passed</em> would write — not what a run with
     * no matcher at all would write, which removes nothing. The removal the registration drives is still applied;
     * only its assertion is deferred.
     */
    @Test
    public void regeneratesPastAFailingWithAndWritesWhatAPassingMatcherWouldHave() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .with("beanInteger", Matchers.equalTo(999));

            MatcherAssert.assertThat(actual, underTest);

            assertApprovedFileIs(imfsi, REGENERATED_WITHOUT_INTEGER);
        });
    }

    @Test
    public void regeneratesPastAFailingWithMatcher() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .withMatcher(Matchers.equalTo("beanInteger"), Matchers.equalTo(999));

            MatcherAssert.assertThat(actual, underTest);

            assertApprovedFileIs(imfsi, REGENERATED_WITHOUT_INTEGER);
        });
    }

    /**
     * The additional mode keeps its field, so a skipped run writes the very value its matcher rejects. That is
     * inherent: a custom-matcher verdict comes from the actual data, and no regeneration can fix one. The second
     * half is the point — the failure returns the moment the flag is not in play.
     */
    @Test
    public void regeneratesPastAFailingAlsoCheckAndCementsTheRejectedValue() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);

            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .alsoCheck("beanInteger", Matchers.equalTo(999)));

            assertApprovedFileIs(imfsi, REGENERATED_WITH_INTEGER);

            assertThrows(AssertionError.class, () -> MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), getDefaultFileMatcherConfig())
                    .alsoCheck("beanInteger", Matchers.equalTo(999))));
        });
    }

    @Test
    public void regeneratesPastAFailingAlsoCheckMatching() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);

            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .alsoCheckMatching(Matchers.equalTo("beanInteger"), Matchers.equalTo(999)));

            assertApprovedFileIs(imfsi, REGENERATED_WITH_INTEGER);

            assertThrows(AssertionError.class, () -> MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), getDefaultFileMatcherConfig())
                    .alsoCheckMatching(Matchers.equalTo("beanInteger"), Matchers.equalTo(999))));
        });
    }

    /** A path that names nothing threw out of the evaluation; with that skipped, regeneration proceeds. */
    @Test
    public void regeneratesPastAPathThatNamesNothing() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .with("noSuchField", Matchers.notNullValue());

            MatcherAssert.assertThat(actual, underTest);

            assertApprovedFileIs(imfsi, REGENERATED_WITH_INTEGER);
        });
    }

    /**
     * Removal under the flag has to reach a nested path, not only a top-level scalar — and the invariant is
     * stated directly: the file a <em>failing</em> matcher regenerates is the one a <em>passing</em> matcher
     * would have regenerated. Anything weaker would not notice removal being suppressed along with evaluation.
     */
    @Test
    public void regeneratesPastAFailingMatcherOnANestedPath() {
        Person actual = PreBuilt.getPerson();
        String[] written = new String[2];

        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), HEADER + "{\n  \"drifted\": true\n}");
            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .with("currentAddress.city", Matchers.equalTo("nowhere")));
            written[0] = getFiles(imfsi).get(0).getContent();
        });

        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), HEADER + "{\n  \"drifted\": true\n}");
            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwrite())
                    .with("currentAddress.city", Matchers.notNullValue()));
            written[1] = getFiles(imfsi).get(0).getContent();
        });

        Assertions.assertEquals(written[1], written[0]);
        Assertions.assertTrue(written[0].contains("\"currentAddress\""), written[0]);
    }

    /**
     * The flag applies to the run, not only to the files that turn out to need rewriting. A test whose approved
     * file is already current has its matchers skipped too, so it passes where it would otherwise have failed.
     * That is the cost of asking for the flag and the reason it is off by default: an update run produces files,
     * and a verification run is what decides whether they are right — as the second half here shows.
     */
    @Test
    public void alsoSkipsTheMatcherForAFileThatNeededNoRewrite() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), REGENERATED_WITHOUT_INTEGER);

            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .with("beanInteger", Matchers.equalTo(999)));

            assertApprovedFileIs(imfsi, REGENERATED_WITHOUT_INTEGER);

            AssertionError thrown = assertThrows(AssertionError.class,
                    () -> MatcherAssert.assertThat(actual, MATCHER_FACTORY
                            .jsonMatcher(dummyInformation(imfsi), getDefaultFileMatcherConfig())
                            .with("beanInteger", Matchers.equalTo(999))));
            Assertions.assertTrue(thrown.getMessage().endsWith("but: beanInteger was <4>"), thrown.getMessage());
        });
    }

    /** The same for the name-pattern form. */
    @Test
    public void alsoSkipsAPatternFormMatcherForAFileThatNeededNoRewrite() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), REGENERATED_WITHOUT_INTEGER);

            MatcherAssert.assertThat(actual, MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .withMatcher(Matchers.equalTo("beanInteger"), Matchers.equalTo(999)));

            assertApprovedFileIs(imfsi, REGENERATED_WITHOUT_INTEGER);
        });
    }

    // --- what it deliberately does not do ---

    /**
     * A path the removal machinery rejects is still rejected, and the flag does not change that. The two routes
     * agreeing does not by itself prove which one raised — that is settled by reading ignorePath — but it does
     * record that a custom matcher's path is treated no differently from an ignore's.
     */
    @Test
    public void stillThrowsForAPathCrossingAPrimitive() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);

            IllegalArgumentException viaCustomMatcher = assertThrows(IllegalArgumentException.class,
                    () -> MatcherAssert.assertThat(actual, MATCHER_FACTORY
                            .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                            .with("beanChar.subpath", Matchers.notNullValue())));

            IllegalArgumentException viaIgnoring = assertThrows(IllegalArgumentException.class,
                    () -> MatcherAssert.assertThat(actual, MATCHER_FACTORY
                            .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                            .ignoring("beanChar.subpath")));

            Assertions.assertEquals("beanChar.subpath does not exist", viaCustomMatcher.getMessage());
            Assertions.assertEquals(viaIgnoring.getMessage(), viaCustomMatcher.getMessage());
        });
    }

    /**
     * The scoping guard. Asserting only that something threw is not enough here: were the in-place half of the
     * condition dropped, the matcher would be deferred, the comparison would fail, and an {@code AssertionError}
     * would come out either way. Which message it carries is what tells the two apart — the custom matcher's,
     * not a JSON diff.
     */
    @Test
    public void hasNoEffectWithoutAnInPlaceUpdate() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), skipCustomMatchersWithoutInPlaceOverwrite())
                    .with("beanInteger", Matchers.equalTo(999));

            AssertionError thrown = assertThrows(AssertionError.class,
                    () -> MatcherAssert.assertThat(actual, underTest));

            Assertions.assertTrue(thrown.getMessage().endsWith("but: beanInteger was <4>"), thrown.getMessage());
            assertApprovedFileIs(imfsi, DRIFTED);
        });
    }

    /**
     * The default, stated locally. Duplicates the intent of the test added alongside the behaviour in 9d430aa,
     * so this file says what happens when the flag is absent rather than only what happens when it is set.
     */
    @Test
    public void withoutTheFlagAFailingCustomMatcherStillBlocksTheRewrite() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwrite())
                    .with("beanInteger", Matchers.equalTo(999));

            assertThrows(AssertionError.class, () -> MatcherAssert.assertThat(actual, underTest));

            assertApprovedFileIs(imfsi, DRIFTED);
        });
    }

    /** A matcher that holds behaves exactly as it does today. */
    @Test
    public void aPassingCustomMatcherIsUnaffectedByTheFlag() {
        BeanWithPrimitives actual = getBeanWithPrimitives();
        inMemoryUnixFs(imfsi -> {
            writeFile(approvedFile(imfsi), DRIFTED);
            JsonMatcher<Object> underTest = MATCHER_FACTORY
                    .jsonMatcher(dummyInformation(imfsi), enableInPlaceOverwriteSkippingCustomMatchers())
                    .with("beanInteger", Matchers.equalTo(4));

            MatcherAssert.assertThat(actual, underTest);

            assertApprovedFileIs(imfsi, REGENERATED_WITHOUT_INTEGER);
        });
    }

}
