package com.github.karsaig.approvalcrest.matcher.types;

import com.github.karsaig.approvalcrest.matcher.AbstractFileMatcherTest;
import com.github.karsaig.approvalcrest.matcher.GsonConfiguration;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.junit.jupiter.api.Test;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Optional;

/**
 * Tests that approvalcrest correctly serializes objects containing generic types
 * when a TypeAdapterFactory (such as those generated by Immutables @Gson.TypeAdapters)
 * requires actual type parameters and throws IllegalStateException on raw types.
 */
class GenericTypeAdapterSerializationTest extends AbstractFileMatcherTest {

    /**
     * A generic container similar to Immutables-generated types.
     */
    public static class GenericContainer<T> {
        private String label;
        private List<T> items;

        public GenericContainer() {
        }

        public GenericContainer(String label, List<T> items) {
            this.label = label;
            this.items = items;
        }

        public String getLabel() {
            return label;
        }

        public void setLabel(String label) {
            this.label = label;
        }

        public List<T> getItems() {
            return items;
        }

        public void setItems(List<T> items) {
            this.items = items;
        }
    }

    /**
     * Mimics what Immutables generates: ImmutableFoo extends Foo.
     * When Gson encounters this as a field value, it uses the runtime class
     * (ImmutableGenericContainer) instead of the declared type (GenericContainer&lt;String&gt;),
     * causing the TypeAdapterFactory to receive a raw TypeToken.
     */
    public static class ImmutableGenericContainer<T> extends GenericContainer<T> {
        public ImmutableGenericContainer() {
        }

        public ImmutableGenericContainer(String label, List<T> items) {
            super(label, items);
        }
    }

    /**
     * A parent bean that holds an Optional of a generic type.
     * This triggers the JavaOptionalSerializer path.
     */
    public static class BeanWithOptionalGeneric {
        private Optional<GenericContainer<String>> container;

        public BeanWithOptionalGeneric() {
            this.container = Optional.empty();
        }

        public BeanWithOptionalGeneric(GenericContainer<String> container) {
            this.container = Optional.ofNullable(container);
        }

        public Optional<GenericContainer<String>> getContainer() {
            return container;
        }

        public void setContainer(Optional<GenericContainer<String>> container) {
            this.container = container;
        }
    }

    /**
     * A TypeAdapterFactory that mimics the behavior of Immutables-generated factories:
     * it matches on raw type but throws IllegalStateException if the TypeToken
     * does not carry actual type parameters. When type parameters ARE available,
     * it returns null to let Gson use reflective serialization (simulating a factory
     * that only needs to validate type info is present).
     */
    public static class StrictGenericTypeAdapterFactory implements TypeAdapterFactory {
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (GenericContainer.class != type.getRawType()
                    && ImmutableGenericContainer.class != type.getRawType()) {
                return null;
            }
            // Mimics Immutables: requires ParameterizedType
            Type tokenType = type.getType();
            if (!(tokenType instanceof ParameterizedType)) {
                throw new IllegalStateException(
                        "Please supply Type with actual type parameters to serialize "
                                + tokenType + " instance using method overloads like toJson(instance, type). "
                                + "Runtime raw type alone is not enough.");
            }
            // Type params available — return null to let Gson handle reflectively.
            // Real Immutables factories would create their own adapter here.
            return null;
        }
    }

    // --- Test A: JavaOptionalSerializer type propagation ---

    @Test
    void shouldSerializeOptionalGenericFieldWhenTypeAdapterFactoryRequiresTypeParameters() {
        // Use ImmutableGenericContainer to mimic Immutables pattern where runtime type is a subclass
        GenericContainer<String> container = new ImmutableGenericContainer<>("Medications",
                java.util.Arrays.asList("Ibuprofen", "Paracetamol"));
        BeanWithOptionalGeneric actual = new BeanWithOptionalGeneric(container);

        String approvedFileContent = "{\n" +
                "  \"container\": {\n" +
                "    \"value\": {\n" +
                "      \"label\": \"Medications\",\n" +
                "      \"items\": [\n" +
                "        \"Ibuprofen\",\n" +
                "        \"Paracetamol\"\n" +
                "      ]\n" +
                "    }\n" +
                "  }\n" +
                "}";

        GsonConfiguration config = new GsonConfiguration();
        config.addTypeAdapterFactory(new StrictGenericTypeAdapterFactory());

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent,
                jsonMatcher -> jsonMatcher.withGsonConfiguration(config), null);
    }

    @Test
    void shouldSerializeEmptyOptionalGenericFieldWhenTypeAdapterFactoryRequiresTypeParameters() {
        BeanWithOptionalGeneric actual = new BeanWithOptionalGeneric();

        String approvedFileContent = "{\n" +
                "  \"container\": {}\n" +
                "}";

        GsonConfiguration config = new GsonConfiguration();
        config.addTypeAdapterFactory(new StrictGenericTypeAdapterFactory());

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent,
                jsonMatcher -> jsonMatcher.withGsonConfiguration(config), null);
    }

    // --- Test C: LenientTypeAdapterFactory wrapper ---

    @Test
    void shouldSerializeDirectGenericFieldWithLenientFallbackWhenFactoryThrowsOnRawType() {
        // When a generic object is the TOP-LEVEL input to assertThat,
        // gson.toJsonTree(object) uses object.getClass() which is raw.
        // The factory receives a raw TypeToken and throws.
        // The lenient wrapper should catch this and fall back to reflective serialization.
        GenericContainer<String> actual = new ImmutableGenericContainer<>("Allergies",
                java.util.Arrays.asList("Penicillin", "Pollen"));

        String approvedFileContent = "{\n" +
                "  \"items\": [\n" +
                "    \"Penicillin\",\n" +
                "    \"Pollen\"\n" +
                "  ],\n" +
                "  \"label\": \"Allergies\"\n" +
                "}";

        GsonConfiguration config = new GsonConfiguration();
        config.addTypeAdapterFactory(new StrictGenericTypeAdapterFactory());

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent,
                jsonMatcher -> jsonMatcher.withGsonConfiguration(config), null);
    }

    @Test
    void shouldSerializeNonSubclassGenericDirectlyWithLenientFallbackWhenFactoryThrowsOnRawType() {
        // Same scenario but with GenericContainer directly (not subclass) — the factory
        // also receives a raw type from gson.toJsonTree(object).
        GenericContainer<String> actual = new GenericContainer<>("Diagnoses",
                java.util.Arrays.asList("Diagnosis A"));

        String approvedFileContent = "{\n" +
                "  \"items\": [\n" +
                "    \"Diagnosis A\"\n" +
                "  ],\n" +
                "  \"label\": \"Diagnoses\"\n" +
                "}";

        GsonConfiguration config = new GsonConfiguration();
        config.addTypeAdapterFactory(new StrictGenericTypeAdapterFactory());

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent,
                jsonMatcher -> jsonMatcher.withGsonConfiguration(config), null);
    }

    // --- Tests for Optional<Interface> and Optional<AbstractClass> bug ---

    public interface UrlDto {
        String getUrl();
        String getLabel();
    }

    public static class UrlDtoImpl implements UrlDto {
        private final String url;
        private final String label;

        public UrlDtoImpl(String url, String label) {
            this.url = url;
            this.label = label;
        }

        @Override
        public String getUrl() {
            return url;
        }

        @Override
        public String getLabel() {
            return label;
        }
    }

    public static abstract class AbstractTeamDTO {
        public abstract String getTeamName();
        public abstract int getMemberCount();
    }

    public static class ConcreteTeamDTO extends AbstractTeamDTO {
        private final String teamName;
        private final int memberCount;

        public ConcreteTeamDTO(String teamName, int memberCount) {
            this.teamName = teamName;
            this.memberCount = memberCount;
        }

        @Override
        public String getTeamName() {
            return teamName;
        }

        @Override
        public int getMemberCount() {
            return memberCount;
        }
    }

    public static class BeanWithOptionalInterface {
        private Optional<UrlDto> link;

        public BeanWithOptionalInterface(UrlDto link) {
            this.link = Optional.ofNullable(link);
        }

        public Optional<UrlDto> getLink() {
            return link;
        }
    }

    public static class BeanWithOptionalAbstract {
        private Optional<AbstractTeamDTO> team;

        public BeanWithOptionalAbstract(AbstractTeamDTO team) {
            this.team = Optional.ofNullable(team);
        }

        public Optional<AbstractTeamDTO> getTeam() {
            return team;
        }
    }

    @Test
    void shouldSerializeOptionalOfInterfaceTypeUsingRuntimeType() {
        BeanWithOptionalInterface actual = new BeanWithOptionalInterface(
                new UrlDtoImpl("https://example.com", "Example"));

        String approvedFileContent = "{\n" +
                "  \"link\": {\n" +
                "    \"value\": {\n" +
                "      \"url\": \"https://example.com\",\n" +
                "      \"label\": \"Example\"\n" +
                "    }\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalOfAbstractTypeUsingRuntimeType() {
        BeanWithOptionalAbstract actual = new BeanWithOptionalAbstract(
                new ConcreteTeamDTO("Engineering", 42));

        String approvedFileContent = "{\n" +
                "  \"team\": {\n" +
                "    \"value\": {\n" +
                "      \"teamName\": \"Engineering\",\n" +
                "      \"memberCount\": 42\n" +
                "    }\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    // --- Tests for polymorphic base class ---

    public static class Animal {
        private final String name;
        private final int legs;

        public Animal(String name, int legs) {
            this.name = name;
            this.legs = legs;
        }

        public String getName() { return name; }
        public int getLegs() { return legs; }
    }

    public static class Dog extends Animal {
        private final String breed;

        public Dog(String name, int legs, String breed) {
            super(name, legs);
            this.breed = breed;
        }

        public String getBreed() { return breed; }
    }

    public static class BeanWithOptionalAnimal {
        private Optional<Animal> pet;

        public BeanWithOptionalAnimal(Animal pet) {
            this.pet = Optional.ofNullable(pet);
        }

        public Optional<Animal> getPet() { return pet; }
    }

    @Test
    void shouldSerializeOptionalOfConcreteBaseClassUsingRuntimeTypeWhenSubclassPresent() {
        BeanWithOptionalAnimal actual = new BeanWithOptionalAnimal(
                new Dog("Rex", 4, "Labrador"));

        String approvedFileContent = "{\n" +
                "  \"pet\": {\n" +
                "    \"value\": {\n" +
                "      \"breed\": \"Labrador\",\n" +
                "      \"name\": \"Rex\",\n" +
                "      \"legs\": 4\n" +
                "    }\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalOfConcreteClassWhenExactTypeMatches() {
        BeanWithOptionalAnimal actual = new BeanWithOptionalAnimal(
                new Animal("Cat", 4));

        String approvedFileContent = "{\n" +
                "  \"pet\": {\n" +
                "    \"value\": {\n" +
                "      \"name\": \"Cat\",\n" +
                "      \"legs\": 4\n" +
                "    }\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    // --- Test for Optional<List<T>> (interface type parameter) ---

    public static class BeanWithOptionalList {
        private Optional<List<String>> tags;

        public BeanWithOptionalList(List<String> tags) {
            this.tags = Optional.ofNullable(tags);
        }

        public Optional<List<String>> getTags() { return tags; }
    }

    @Test
    void shouldSerializeOptionalOfListInterface() {
        BeanWithOptionalList actual = new BeanWithOptionalList(
                java.util.Arrays.asList("java", "testing"));

        String approvedFileContent = "{\n" +
                "  \"tags\": {\n" +
                "    \"value\": [\n" +
                "      \"java\",\n" +
                "      \"testing\"\n" +
                "    ]\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    // --- Test for configurable skip types ---

    public static class CustomLibraryType {
        private final String data;

        public CustomLibraryType(String data) {
            this.data = data;
        }

        public String getData() { return data; }
    }

    public static class BeanWithCustomType {
        private CustomLibraryType payload;

        public BeanWithCustomType(CustomLibraryType payload) {
            this.payload = payload;
        }

        public CustomLibraryType getPayload() { return payload; }
    }

    @Test
    void shouldRespectConfigurableSkipTypesInFallbackFactories() {
        BeanWithCustomType actual = new BeanWithCustomType(new CustomLibraryType("hello"));

        String approvedFileContent = "{\n" +
                "  \"payload\": {\n" +
                "    \"data\": \"hello\"\n" +
                "  }\n" +
                "}";

        GsonConfiguration config = new GsonConfiguration();
        config.addTypeToSkipInFallbackFactories(CustomLibraryType.class);

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent,
                jsonMatcher -> jsonMatcher.withGsonConfiguration(config), null);
    }

    // ---- Primitive Optional tests ----

    public static class BeanWithOptionalInt {
        private java.util.OptionalInt count;

        public BeanWithOptionalInt(java.util.OptionalInt count) {
            this.count = count;
        }

        public java.util.OptionalInt getCount() { return count; }
    }

    public static class BeanWithOptionalLong {
        private java.util.OptionalLong bigCount;

        public BeanWithOptionalLong(java.util.OptionalLong bigCount) {
            this.bigCount = bigCount;
        }

        public java.util.OptionalLong getBigCount() { return bigCount; }
    }

    public static class BeanWithOptionalDouble {
        private java.util.OptionalDouble score;

        public BeanWithOptionalDouble(java.util.OptionalDouble score) {
            this.score = score;
        }

        public java.util.OptionalDouble getScore() { return score; }
    }

    @Test
    void shouldSerializeOptionalIntPresent() {
        BeanWithOptionalInt actual = new BeanWithOptionalInt(java.util.OptionalInt.of(42));

        String approvedFileContent = "{\n" +
                "  \"count\": {\n" +
                "    \"value\": 42\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalIntEmpty() {
        BeanWithOptionalInt actual = new BeanWithOptionalInt(java.util.OptionalInt.empty());

        String approvedFileContent = "{\n" +
                "  \"count\": {}\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalLongPresent() {
        BeanWithOptionalLong actual = new BeanWithOptionalLong(java.util.OptionalLong.of(123456789L));

        String approvedFileContent = "{\n" +
                "  \"bigCount\": {\n" +
                "    \"value\": 123456789\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalLongEmpty() {
        BeanWithOptionalLong actual = new BeanWithOptionalLong(java.util.OptionalLong.empty());

        String approvedFileContent = "{\n" +
                "  \"bigCount\": {}\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalDoublePresent() {
        BeanWithOptionalDouble actual = new BeanWithOptionalDouble(java.util.OptionalDouble.of(3.14));

        String approvedFileContent = "{\n" +
                "  \"score\": {\n" +
                "    \"value\": 3.14\n" +
                "  }\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }

    @Test
    void shouldSerializeOptionalDoubleEmpty() {
        BeanWithOptionalDouble actual = new BeanWithOptionalDouble(java.util.OptionalDouble.empty());

        String approvedFileContent = "{\n" +
                "  \"score\": {}\n" +
                "}";

        assertJsonMatcherWithDummyTestInfo(actual, approvedFileContent, null);
    }
}
