package com.github.karsaig.approvalcrest;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Object-graph reference ids are generated by {@code GraphAdapterBuilder} as
 * {@code "0x" + Integer.toHexString(n)}, so from the tenth object onwards they contain the hex
 * letters a-f. {@link FieldsIgnorer#isGraphAdapterKey(String)} is the single definition of that
 * format and must recognise every id the generator can produce.
 */
public class GraphReferenceParsingTest {

    /** Mirrors the id generation in {@code GraphAdapterBuilder}. */
    private static String generatedId(int n) {
        return "0x" + Integer.toHexString(n);
    }

    @Test
    public void recognisesSingleDigitDecimalIds() {
        for (int n = 1; n <= 9; n++) {
            assertTrue(FieldsIgnorer.isGraphAdapterKey(generatedId(n)),
                    "generated id " + generatedId(n) + " must be recognised");
        }
    }

    @Test
    public void recognisesIdsContainingHexLetters() {
        for (int n = 10; n <= 15; n++) {
            assertTrue(FieldsIgnorer.isGraphAdapterKey(generatedId(n)),
                    "generated id " + generatedId(n) + " must be recognised");
        }
    }

    @Test
    public void recognisesHexLetterIdsAtEveryOrderOfMagnitude() {
        for (int n : new int[]{0xa, 0xb, 0xf, 0xa0, 0xff, 0xa00, 0xfff, 0xffff}) {
            assertTrue(FieldsIgnorer.isGraphAdapterKey(generatedId(n)),
                    "generated id " + generatedId(n) + " (object #" + n + ") must be recognised");
        }
    }

    @Test
    public void rejectsThingsThatAreNotReferenceIds() {
        assertFalse(FieldsIgnorer.isGraphAdapterKey(null), "null");
        assertFalse(FieldsIgnorer.isGraphAdapterKey(""), "empty");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("0x"), "prefix with no digits");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("someField"), "an ordinary field name");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("0xg"), "g is not a hex digit");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("0xAB"), "uppercase is not produced by toHexString");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("prefix0x1"), "must match in full, not as a substring");
        assertFalse(FieldsIgnorer.isGraphAdapterKey("0x1suffix"), "must match in full, not as a substring");
    }
}
